export const idiomasAnexo = [
    { label: 'Búlgaro', value: 'bulgaro' },
    { label: 'Checo', value: 'checo' },
    { label: 'Holandés', value: 'holandes' },
    { label: 'Estonio', value: 'estonio' },
    { label: 'Francés', value: 'frances' },
    { label: 'Griego', value: 'griego' },
    { label: 'Irlandés', value: 'irlandes' },
    { label: 'Letón', value: 'leton' },
    { label: 'Maltés', value: 'maltes' },
    { label: 'Portugués', value: 'portugues' },
    { label: 'Eslovaco', value: 'eslovaco' },
    { label: 'Croata', value: 'croata' },
    { label: 'Danés', value: 'danes' },
    { label: 'Inglés', value: 'ingles' },
    { label: 'Finlandés', value: 'finlandes' },
    { label: 'Alemán', value: 'aleman' },
    { label: 'Húngaro', value: 'hungaro' },
    { label: 'Italiano', value: 'italiano' },
    { label: 'Lituano', value: 'lituano' },
    { label: 'Polaco', value: 'polaco' },
    { label: 'Rumano', value: 'rumano' },
    { label: 'Esloveno', value: 'esloveno' },
    { label: 'Sueco', value: 'sueco' },
  ];